### ISSUE TITLE
Update links and layouts to harmonize with revised structure

### ISSUE THREAD

**Issue by othermaciej** [whatwg/whatwg.org#149]
Moved from https://github.com/whatwg/sg/issues/49 on behalf of @geoffcr :

I realize that the front page of the WHATWG at https://whatwg.org/ has "history" and is not likely to change, but - to a novice user - there are some confusing elements to how the links are laid out (and some of the terminology). Here are several - some significant, some less so:

**_Workstreams_**
Where do I find a list of Workstreams? Oh - Standards; we don't call them "Workstreams" anywhere, so far as I can tell. That should presumably be fixed.
(We also might want to change the "Standards" block to say "See the other **Living** Standards developed at the WHATWG".)

**_Policies_**
Where do I find Policies? Oh - if I click on FAQ, Standards, or Participate, there's also a "Policies" tab at the top. Policies deserve a link from the main page, along with Standards and FAQ. ("Working Mode" has its own front-page button, even though it's now a subset of Policies; perhaps that should be swapped out and replaced with Policies?)

**_Signing up_**
"**Participate**" takes me to a nice narrative page, but please point people to the governing Workstream Policy and IPR Policy in addition to the Code of Conduct and the Working Mode. (This strikes me as significant.) 
"**Join**" takes me straight to the repositories instead of to the participation page. That strikes me as confusing. 

**_IRC_**
Do people still use IRC? (In other words, does it merit front-page real estate?)

_**Format**_
This is just a visual nit, but it's disorienting (to me) to fly from the "Nine Colored Blocks" front page to a "Traditional Tabbed" Standards/FAQ/Policies/Participate page, or to the Living Standards in a cleaner HTML presentation. Not sure what to fix, except perhaps to ensure that there's a consistent relationship between the tabbed pages and the front page. 

**_Review Drafts_**
Will we see the latest Review Drafts posted on the Living Standard page? For example, https://html.spec.whatwg.org/multipage/ has links to the one-page version, multipage version, developer version, translations, etc. Will there also be a "Latest Review Draft" button? (I would think so; otherwise, non-technical lawyers are going to have a hard time finding it in the repository.)

**Comment by domenic** [comment]
Great thoughts.

In general we'd love to redesign the homepage. https://github.com/whatwg/whatwg.org/pull/90 was an attempt at this; see a preview at https://jsbin.com/cijufadebe/1/edit?html,css,output. We got stuck there because we weren't sure what to do in this new design with the tabbed pages, but my current thinking is that we'd just keep them as-is until someone had a good idea, and at least make the front page much better. I might work on that today a bit.

> Where do I find a list of Workstreams? Oh - Standards; we don't call them "Workstreams" anywhere, so far as I can tell. That should presumably be fixed.

Personally I think that Workstreams are of less interest to website visitors than the Standards. They're more of an administrative detail. We should probably link to them from the bottom of the Standards page, but I think Standards should stay front and center.

This is somewhat related to https://github.com/whatwg/meta/issues/57.

> Where do I find Policies? Oh - if I click on FAQ, Standards, or Participate, there's also a "Policies" tab at the top. Policies deserve a link from the main page, along with Standards and FAQ. ("Working Mode" has its own front-page button, even though it's now a subset of Policies; perhaps that should be swapped out and replaced with Policies?)

I think Working Mode is the most important policy for someone seeking to understand the work done at the WHATWG, and should be given some prominence. But yes, I think a link to the other policies probably deserves some front-page real-estate too.

> "Participate" takes me to a nice narrative page, but please point people to the governing Workstream Policy and IPR Policy in addition to the Code of Conduct and the Working Mode. (This strikes me as significant.)

Good ideas!

> "Join" takes me straight to the repositories instead of to the participation page. That strikes me as confusing.

I think the link to our GitHub should be framed as, well, a link to GitHub, instead of a link to "Join".

> Do people still use IRC? (In other words, does it merit front-page real estate?)

For sure, it's a very active locus for the WHATWG community. Check out the logs at https://freenode.logbot.info/whatwg/20171221 to get an idea.

> Format

Yeah, not sure what to do there exactly; I wish we had more designers.

> Will we see the latest Review Drafts posted on the Living Standard page?

I think that's [required in the workstream policy](https://github.com/whatwg/sg/blob/master/Workstream%20Policy.md#notice-for-living-standards).

**Comment by annevk** [comment]
I'm okay with the status quo with regards to that. In particular, it reads:

> To participate in the WHATWG and help develop standards and tests, please read the Code of Conduct and Working Mode. Then, sign the Participant Agreement. 

And the Participation Agreement spells out the policies in effect a couple of times.
