### ISSUE TITLE
Consider moving more wiki pages to whatwg.org

### ISSUE THREAD

**Issue by annevk** [whatwg/whatwg.org#162]
Here are the ones that come to mind:

- [x] https://wiki.whatwg.org/wiki/IRC
- [x] https://wiki.whatwg.org/wiki/Style

The one problem I have is that I'm not sure what a good entry point for these pages is within the overall site hierarchy.

**Comment by foolip** [comment]
Redirecting from the wiki is also not entirely straightforward. It could be, of course, but would be done by Apache.

**Comment by annevk** [comment]
Thus far we used a template of sorts: https://wiki.whatwg.org/wiki/FAQ. That seems fine to me.

cc @GPHemsley

**Comment by domenic** [comment]
See also #51.

**Comment by GPHemsley** [comment]
We have two templates:

* https://wiki.whatwg.org/wiki/Template:Obsolete (created in 2012 by me)
* https://wiki.whatwg.org/wiki/Template:Moved (created in 2017 by @zcorpan)

The obsolete template also adds pages to various categories, rooted here: https://wiki.whatwg.org/wiki/Category:Obsolete_documents

There is indeed no convenient way to redirect to an external URL from within MediaWiki, though I think this is actually by design.

**Comment by GloverDonovan** [comment]
If this is still an issue, I can work on moving the style guide (maybe it should read more naturally as well?). Who is the target audience? It may be useful to take inspiration from MDN's [Writing style guide](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Guidelines/Writing_style_guide).

**Comment by annevk** [comment]
@GloverDonovan the audience is folks doing any kind of writing for the WHATWG, including standards, documentation, comments in software, the website, and blog posts. Of those, the primary focus would be the standards and the website.

**Comment by annevk** [comment]
I'd be happy to see it made more accessible, for what it's worth.

**Comment by annevk** [comment]
Closing as other pages that need to be moved (if any) can be done through new issues.

**Comment by annevk** [comment]
Thanks again @GloverDonovan for your efforts here!

**Comment by GloverDonovan** [comment]
A bit late, but glad I could help!
