### ISSUE TITLE
Build: "The requested URL returned error: 400 Bad Request"

### ISSUE THREAD

**Issue by annevk** [whatwg/whatwg.org#227]
So we have https://github.com/whatwg/whatwg.org/blob/master/resources.whatwg.org/build/deploy.sh#L90 specifically to check errors and warnings in Bikeshed and yet somehow at times it returns nothing of use whatsoever.

@plinss @tabatkins what's the way to get it to return a more detailed error message?

(Currently hitting this on whatwg/dom.)

**Comment by domenic** [comment]
Previously, see https://github.com/whatwg/whatwg.org/pull/226#issuecomment-418493892 . As far as I can tell the current set of Bikeshed API configuration would require us to do something like your https://github.com/whatwg/whatwg.org/pull/223; we should probably just merge that pending something better. Details:

- If you set die-on=warning, there is no reliable way to get the output in failure cases unless you set output=err. In particular, even though it will return a 400 status if your document has warnings, the API will give the built-with-warnings HTML output instead of giving you the warning text
- If you set output=err, you always have to do multiple passes in the success case: once to get an empty string output and a 200 status code, and once to get the real output with a 200 status code.
- If you do what you did in #223, using `force=1`, you end up doing multiple passes in both the success and failure cases, because the status code is always 200, so even if there's a warning or error, you'll still try again later on.

So right now it seems like the best you could do would be one extra round-trip on success and zero extra round-trips on failure. #223 does one extra round-trip for both, but it's better than nothing.

Ideally this would be fixed by the API to allow no extra round trips, e.g. by making output=err work with die-on=warning.

**Comment by annevk** [comment]
Okay, let's see what the Bikeshed experts think before merging #223. It'd be nice to resolve within the next few days, but no huge rush.

**Comment by annevk** [comment]
@plinss @tabatkins ping.

**Comment by tabatkins** [comment]
So, the API arguments are pretty sparsely documented, but I'm *assuming* that `die-on` and `force` do the same things as the Bikeshed command-line args. (And that `force=1` is thus just a synonym for `die-on=nothing`.)

Then, `output` just controls whether the returned result is the built `.html` file, or the console output, right?

So, what exactly do you want in different cases? I can't quite parse it out of @domenic's list, as it's all mixed in with their experiments with the different flags. It *kinda* sounds like they want an output mode that produces the HTML upon success, but the console output upon failure; a conditional blending of the two output modes, presumably with the HTTP Status Code differentiating between them (`200` vs `400`). Right?  (And, probably, have it auto-run as `force` so you get *all* the errors, rather than just the first one?)

**Comment by domenic** [comment]
Right. What I want is mode where:

- Warnings and errors are both treated as failure
- Failure gives a 400 status code with the warning/error messages as the response body
- Success gives a 200 status code with the output HTML as the response body

**Comment by plinss** [comment]
> So, the API arguments are pretty sparsely documented, but I'm assuming that die-on and force do the same things as the Bikeshed command-line args. (And that force=1 is thus just a synonym for die-on=nothing.)

Correct. Most of the arguments are simple pass-throughs to bikeshed command-line args.

> Then, output just controls whether the returned result is the built .html file, or the console output, right?

Also correct, however there should be a way to do what @domenic wants as well via content negotiation. When using `output=html` (which is the default), then the output is actually determined by the `Accept` header and the available content. If you send an `Accept` header of `text/plain, text/html` then you should get console output if any, otherwise the built .html file.

The status code is determined by bikeshed's return code, so if bikeshed is set to `die-on=warning` then any warning should produce a 400 status code.

**Comment by annevk** [comment]
Aah okay, we should be able to add an `Accept` header when we check for warnings.

**Comment by domenic** [comment]
Thanks all! https://github.com/whatwg/whatwg.org/pull/229 should do the trick, then. I tested it in the success, warning, and error scenarios and it seems to do the right thing in all cases.

Next up: trying to figure out how to avoid the `\033[1;33m` spew in the console...

**Comment by plinss** [comment]
I'd have to add an additional argument to suppress the console color escapes

**Comment by domenic** [comment]
I'm hoping we can actually print them to the console. I'm wondering if maybe we're getting back the literal string "\033" instead of the 0x1B byte? Or, maybe it's something where terminals don't like to pipe things from curl directly into their TTY. Need to dig in further.

**Comment by tabatkins** [comment]
Yeah, the *default* output mode is console, which outputs ANSI escape codes. It's absolutely not meant for plain-text consumption.

@plinss, you should probably just unreservedly pass `--print=plain`, it'll give the same output but without the escape sequences. I don't think there's a good reason to ever display the console codes.

**Comment by plinss** [comment]
Ah, interesting, yeah it wasn't handling the string escapes properly on the server and was sending them literally, should be fixed

**Comment by plinss** [comment]
> @plinss, you should probably just unreservedly pass --print=plain, it'll give the same output but without the escape sequences. I don't think there's a good reason to ever display the console codes.

I actually pass `--print=markup` and process it myself, for the case where you're sending the error output with a `text/html``Accept` header you get proper html...

**Comment by tabatkins** [comment]
Ah, cool.

**Comment by domenic** [comment]
Oh sweet, those server changes seem to have fixed it!
