### ISSUE TITLE
Lint for tabs

### ISSUE THREAD

**Issue by annevk** [whatwg/whatwg.org#246]
Apparently in https://github.com/whatwg/html/pull/4455 tabs got into a source document somehow. That'd be easy to prevent via linting.

**Comment by annevk** [comment]
There's potentially a whole blocklist here I suppose, but only addressing the known issues for now seems fine.

**Comment by domenic** [comment]
There are a few things to figure out here:

- build.sh in this repository doesn't seem to fail the build on lint errors. It just prints them. That's weird.
- build.sh in this repository inlines the lint script. This is separate from https://github.com/whatwg/html-build/blob/master/lint.sh. Should we merge them?
  - Pro: shared linting heuristics
  - Con: makes html-build a bit more complicated and slow, since it needs to download the lint script on every use. (Or we could download it only on first use, but then we'll have out of sync local lint scripts.) 
  - Con: slight duplication of effort and complications, e.g. html-build needs manual RFC 2119 linting but Bikeshed does that for us here; html-build has an extra lint line for "Possible copypasta" that does not appear here.

I'll update the script here but we should either leave this open or open a new issue for html-build, especially since the original issue was about a html PR.
