### ISSUE TITLE
Review Drafts issue

### ISSUE THREAD

**Issue by annevk** [whatwg/whatwg.org#348]
@domenic @foolip so I'm not sure what's going wrong, but Review Drafts are not building correctly, e.g., https://github.com/whatwg/dom/pull/936. Looking at https://github.com/whatwg/whatwg.org/blob/master/resources.whatwg.org/build/deploy.sh I don't really understand where we pass the correct `.bs` file to bikeshed. It seems it always uses INPUT_FILE somehow?

I guess a fallback would be to manually split these PRs into two. One for the RD and one for updating the original file. That will likely work given it worked last month.

**Comment by andreubotella** [comment]
See https://github.com/tabatkins/bikeshed/issues/1818#issuecomment-749145077

**Comment by annevk** [comment]
Thanks so much for your help with this @andreubotella!

I'm still not sure how `deploy.sh` picks up the RD Bikeshed source file though. I guess we can check whether the publication date ends up being the 21st of December as per:
```diff
--- ./index.bs	2020-12-21 18:39:13.000000000 +0100
+++ review-drafts/2020-12.bs	2020-12-21 18:39:13.000000000 +0100
@@ -1,5 +1,6 @@
 <pre class="metadata">
 Group: WHATWG
+Date: 2020-12-21
 H1: Console
 Shortname: console
 Text Macro: TWITTER consolelog
```

**Comment by annevk** [comment]
So yeah, https://console.spec.whatwg.org/review-drafts/2020-12/ suggests it's published the 24th. Hmm.

**Comment by domenic** [comment]
It does seem that `deploy.sh` is not actually using `review-drafts/whatever.bs` as the input. Instead it's using the living-spec BS file as the input, but using `md-Status="RD"` to override that. And because of how cool our templates are, that's actually enough.

Ideally all our review draft `.bs` files would have `Status: RD` in them. And they would be fed directly into Bikeshed. Hmm. Maybe we can try to fix this and then test it live next time?

**Comment by annevk** [comment]
It also ends up changing the publication date unfortunately.

**Comment by domenic** [comment]
I think that's just because it's using the current date as the publication date, since there's no `Date:` metadata in the living-spec BS file.
