### ISSUE TITLE
Be mobile-friendly

### ISSUE THREAD

**Issue by domenic** [whatwg/whatwg.org#59]
We need a meta viewport tag, and possible some different header/tabbed pages styles

**Comment by annevk** [comment]
I tried to shrink the design, but it actually makes it looks worse on mobile than how it renders today (which is reasonable but small, so likely hard to read for some folks). I suspect we'd need a new design and maybe a simplification of the `<h1>` as it's rather wordy for a small screen.

**Comment by domenic** [comment]
Agreed. While we're redesigning, IMO it'd be nice to put the logo on each page in a corner or similar.

**Comment by zouhir** [comment]
I think this is a good opportunity to slightly improve the current design, colors and overall feels into a more modern color palette and design. I'd break this into 5 tasks:

- Mobile friendly meta tags with initial scale 1.0 and no max scale so users can zoom.
- proper layout for home page which will break once we go mobile responsive.
- solution for tabbed page alternative (important to have).
- Logo on each page (@domenic  comment above)
- new website color palette (nice to have).

### Logo on each page

Do you mean just have an SVG logo instead of the large h1 on the tabbed pages?

### options for tabbed page (kind of important to have):

- off-canvas nav bar to the **left** side with full page height.
- same off-canvas nav bar but to the **right**.
- off canvas drop from the top with dynamic height (won't cover the page)

### options for colors (less important for now)

I quite like the plain white background for content rich websites like this one however we can play with the front page colors as a start.
here's some colors for inspiration:
![inspirations](https://user-images.githubusercontent.com/5052316/29714696-92467246-89e7-11e7-989d-30c38105bec6.png)

**Comment by domenic** [comment]
Yeah, definitely a redesign would be welcome. In general for these sorts of things, anyone who is willing to do the work gets to pick how it looks; I don't think anyone here holds strong opinions on nav bar placement or design.

> Do you mean just have an SVG logo instead of the large h1 on the tabbed pages?

I don't think I'd get rid of the h1 entirely, but maybe it should be shrunken to just "The WHATWG" on mobile or something.

My main issue was that our beloved logo is just completely missing while you read important non-home pages like https://whatwg.org/working-mode .

**Comment by annevk** [comment]
In case it was unclear, the logo is https://resources.whatwg.org/logo.svg.

**Comment by zouhir** [comment]
thanks @domenic @annevk, I might be able to assist here and the yeah logo is very clear 😅  #beauty

**Comment by o-t-w** [comment]
I've had a go at the frontpage. Merge if you like it

**Comment by zouhir** [comment]
Sorry I was busy with university work! thanks so much I'll look 😄
