### ISSUE TITLE
n.whatwg.org issues

### ISSUE THREAD

**Issue by annevk** [whatwg/whatwg.org#84]
- [x] The `formdata` resource is no longer rendered as `text/plain`.
- [x] The Index listing has `../` as an item.

**Comment by foolip** [comment]
@sideshowbarker

**Comment by annevk** [comment]
Is the ../ some kind of nginx-style? Also, what's up with not being able to generate valid HTML in 2017 for these kind of indexes?

**Comment by sideshowbarker** [comment]
> Is the ../ some kind of nginx-style?

It’s the style we get from the default `autoindex`. But there’s an optional `fancyindex` we can enable that suppresses the `../` (and that makes the listings interactively sortable).

> Also, what's up with not being able to generate valid HTML in 2017 for these kind of indexes?

Indeed. I guess I’ll do a PR against the nginx sources (and the `fancyindex` sources to, since it has the same problem) to make it generate valid HTML for indexes.

Anyway, I have  `fancyindex` (https://github.com/whatwg/misc-server/pull/14) enabled now on, so you can go to, e.g., https://n.whatwg.org/ and https://images.whatwg.org/ and https://resources.whatwg.org/ to see what it looks like.

**Comment by annevk** [comment]
Looks a little ugly, but not objectionably so.

**Comment by annevk** [comment]
(Oh, and thanks for looking into this!)

**Comment by domenic** [comment]
That's way nicer than Apache :). With some extra configuration we could even add our own CSS to make it WHATWG green instead of brown!

**Comment by sideshowbarker** [comment]
> With some extra configuration we could even add our own CSS to make it WHATWG green instead of brown!

Indeed. Raised https://github.com/whatwg/resources.whatwg.org/issues/64 so we don’t forget

**Comment by sideshowbarker** [comment]
>> Also, what's up with not being able to generate valid HTML in 2017 for these kind of indexes?
>
> Indeed. I guess I’ll do a PR against the nginx sources (and the `fancyindex` sources to, since it has the same problem) to make it generate valid HTML for indexes.

Happy to discover that this has already been fixed for `fancyindex` upstream:

* https://github.com/aperezdc/ngx-fancyindex/issues/52
* https://github.com/aperezdc/ngx-fancyindex/commit/bdaceb65838cc84e3f34ce490bdd2ce613860a4a
* https://github.com/aperezdc/ngx-fancyindex/commit/c5deb79e8f253e7c42c43a540d0906c17fbe5a90
* https://github.com/aperezdc/ngx-fancyindex/releases/tag/v0.4.2

…released only 25 days ago, so we’ll just need to wait for the Debian package to get updated.

**Comment by annevk** [comment]
This was fixed by https://github.com/whatwg/misc-server/commit/3d3e364df2fb16d3ab6927526b37f1652ca6ab01.
